import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import Provider from '@/components/providers/Provider'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mon',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dark:bg-initial-dark bg-initial-light text-light dark:text-dark w-full txt-initial ${montserrat.variable} font-mon`}>
        <Provider>
          <Navbar />
          <main className='mt-36'>
            {children}
          </main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
